ERROR - 2022-11-15 06:04:11 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in F:\WEB\XAMPP\htdocs\wwegis\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 F:\WEB\XAMPP\htdocs\wwegis\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'root', '', 'wwegis', 3306, '', 0)
#1 F:\WEB\XAMPP\htdocs\wwegis\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 F:\WEB\XAMPP\htdocs\wwegis\vendor\codeigniter4\framework\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 F:\WEB\XAMPP\htdocs\wwegis\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 F:\WEB\XAMPP\htdocs\wwegis\vendor\codeigniter4\framework\system\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
#5 F:\WEB\XAMPP\htdocs\wwegis\vendor\codeigniter4\framework\system\BaseModel.php(623): CodeIgniter\Model->doFirst()
#6 F:\WEB\XAMPP\htdocs\wwegis\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
#7 F:\WEB\XAMPP\htdocs\wwegis\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#8 F:\WEB\XAMPP\htdocs\wwegis\vendor\myth\auth\src\Controllers\AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#9 F:\WEB\XAMPP\htdocs\wwegis\vendor\codeigniter4\framework\system\CodeIgniter.php(927): Myth\Auth\Controllers\AuthController->attemptLogin()
#10 F:\WEB\XAMPP\htdocs\wwegis\vendor\codeigniter4\framework\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#11 F:\WEB\XAMPP\htdocs\wwegis\vendor\codeigniter4\framework\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 F:\WEB\XAMPP\htdocs\wwegis\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 F:\WEB\XAMPP\htdocs\wwegis\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('F:\\WEB\\XAMPP\\ht...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in F:\WEB\XAMPP\htdocs\wwegis\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 F:\WEB\XAMPP\htdocs\wwegis\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 F:\WEB\XAMPP\htdocs\wwegis\vendor\codeigniter4\framework\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 F:\WEB\XAMPP\htdocs\wwegis\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 F:\WEB\XAMPP\htdocs\wwegis\vendor\codeigniter4\framework\system\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
#4 F:\WEB\XAMPP\htdocs\wwegis\vendor\codeigniter4\framework\system\BaseModel.php(623): CodeIgniter\Model->doFirst()
#5 F:\WEB\XAMPP\htdocs\wwegis\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
#6 F:\WEB\XAMPP\htdocs\wwegis\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#7 F:\WEB\XAMPP\htdocs\wwegis\vendor\myth\auth\src\Controllers\AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#8 F:\WEB\XAMPP\htdocs\wwegis\vendor\codeigniter4\framework\system\CodeIgniter.php(927): Myth\Auth\Controllers\AuthController->attemptLogin()
#9 F:\WEB\XAMPP\htdocs\wwegis\vendor\codeigniter4\framework\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#10 F:\WEB\XAMPP\htdocs\wwegis\vendor\codeigniter4\framework\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 F:\WEB\XAMPP\htdocs\wwegis\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 F:\WEB\XAMPP\htdocs\wwegis\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('F:\\WEB\\XAMPP\\ht...')
#13 {main}
CRITICAL - 2022-11-15 06:04:11 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `username` = :username:
AND `users`.`deleted_at` IS NULL
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(623): CodeIgniter\Model->doFirst()
 5 VENDORPATH\myth\auth\src\Authentication\LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
 6 VENDORPATH\myth\auth\src\Authentication\LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate([...], true)
 7 VENDORPATH\myth\auth\src\Controllers\AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt([...], false)
 8 SYSTEMPATH\CodeIgniter.php(927): Myth\Auth\Controllers\AuthController->attemptLogin()
 9 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
10 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
